language: node_js

node_js:
  - "stable"

  addons:
    chrome: stable
    apt:
     packages:
     - libgconf-2-4

install:
  - npm ci

before_script:
  - npm start -- --silent &

script:
  - npm run cypress:run
  
