version: 2
jobs:
  build:
    docker:
      - image: cypress/included:4.5.0
    steps:
      - run: 
          name: cypress run 
          command:  cypress run --spec 'cypress/integration/e2e_tests/*' --browser chrome

workflows: 
  version: 2
  cypress-test:
    jobs:
      - build 